version: "3"
services:
  server:
    build: ./server
    command: "python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./server/:/app
    ports:
      - "8080:8080"
  client:
    image: node:18
    environment:
      - BE_HOST=http://server
    volumes:
      - ./client/:/app
    working_dir: /app
    command: ["sh", "-c", "yarn && yarn start"]
    ports:
      - "3000:3000"
