# Generated by Django 3.2.4 on 2022-09-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(unique=True)),
                ("email", models.TextField(unique=True)),
                ("photoUrl", models.TextField()),
                ("password", models.TextField()),
                ("salt", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("firstName", models.TextField()),
                ("lastName", models.TextField()),
                ("country", models.TextField()),
                ("bio", models.TextField()),
                ("receiveNotifications", models.BooleanField(default=False)),
                ("receiveUpdates", models.BooleanField(default=False)),
                ("completedOnboarding", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
