name: CI
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install server
        working-directory: ./server
        run: pip install -r requirements.txt
      - name: Create env file
        working-directory: ./server
        run: |
          touch .env
          echo SECRET_KEY=test >> .env
      - name: Run server tests
        working-directory: ./server
        run: python manage.py test
  build-and-test-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - name: Install client
        working-directory: ./client
        run: yarn install --frozen-lockfile
      - name: Run client tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./client
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
